// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

console.log("Make it run");

console.log("I hope this work");

console.log("It is cool not you are working");

/*  Not a pure module */
